version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nbddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: haslo
    ports:
      - "5434:5432"
    volumes:
      - pg:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
     - "8080:80"
    depends_on:
     -  db
    volumes:
     - pgadmin-data:/var/lib/pgadmin
volumes:
  pg:
  pgadmin-data:
