version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nbddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: haslo
    ports:
      - "5434:5432"
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
